language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install virtualenv
  - pip install -r requirements.txt

script:
  - bash ./test.sh

notifications:
  email: false # Mute email notification
