# -*- coding: utf-8 -*-
# all available properties in serverless.yml when provider is aws
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service:
  name: {{ cookiecutter.package_slug }}

provider:
  name: aws
  runtime: python{{ cookiecutter._dev_py_ver_major }}.{{ cookiecutter._dev_py_ver_minor }}
  stage: dev
  region: us-east-1
  profile: {{ cookiecutter.aws_profile_name }}
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: {{ cookiecutter.deployment_s3_bucket_name }}
  deploymentPrefix: serverless
  role: "<put-your-own-lambda-iam-role-arn-here>"
  versionFunctions: false

package:
  artifact: ./build/lambda/source.zip

functions:
  my_func:
    handler: {{ cookiecutter.package_name }}.handlers.my_func.handler
    description:
    layers:
      - "<put-your-own-lambda-layers-arn-here>"
