# -*- coding: utf-8 -*-
# all available properties in serverless.yml when provider is aws
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service:
  name: {{ cookiecutter.package_name_slug }}

provider:
  name: aws
  runtime: python{{ cookiecutter._dev_py_ver_major }}.{{ cookiecutter._dev_py_ver_minor }}
  stage: dev
  region: us-east-1
  profile: {{ cookiecutter.aws_profile_name }}
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: {{ cookiecutter.deployment_s3_bucket_name }}
  deploymentPrefix: serverless
  role: arn:aws:iam::{{ cookiecutter.aws_account_id }}:role/cookiecutter-pygitrepo-test # CHANGE THIS
  versionFunctions: false
  environment:
    # Inject non-sensitive config into lambda runtime environment variable.
    # for sensitive config, use secret manager.
    PYGITREPO_PROJECT_NAME: ${file(./config/config-final-for-serverless.json):PROJECT_NAME}

package:
  artifact: ./build/lambda/source.zip

functions:
  my_func:
    handler: {{ cookiecutter.package_name }}.handlers.my_func.handler
    description:
    layers:
      - "arn:aws:lambda:{{ cookiecutter.aws_region }}:{{ cookiecutter.aws_account_id }}:layer:{{ cookiecutter.package_name }}:1" # CHANGE THIS
