use_python368_docker: &use_python368_docker
  docker:
    - image: circleci/python:3.6.8


version: 2
jobs:
  # Check out source code and cache
  check_out_source_code:
    <<: *use_python368_docker
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
              - .

  # General Python Library Open Source Project
  test_aws_lambda_project:
    <<: *use_python368_docker
    steps:
      - attach_workspace:
          at: .
      - run:
          name:
          command: |
            sudo pip install -r requirements.txt # install cookiecutter
            cd ./tests
            bash ./e99_serverless_project.sh
          no_output_timeout: "30s"

workflows:
  version: 2
  build_and_test:
    jobs:
      - check_out_source_code
      - test_aws_lambda_project:
          requires:
            - check_out_source_code
